# Generated by Django 4.1.4 on 2022-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_options_myuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
