# Generated by Django 4.1.4 on 2022-12-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='trailers'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
